# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
      small:
        quality: 75
        filters:
          scale: 
            dim: [210, 140]
      mid:
        quality: 75
        filters:
          scale:
            dim: [340, 177]
      big:
        filters:
          scale:
            dim: [600, 300]
