<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\ResetInfoType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\src\\Form\\ResetInfoType.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\Security.php';

return $this->privates['App\\Form\\ResetInfoType'] = new \App\Form\ResetInfoType(new \Symfony\Component\Security\Core\Security(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
], [
    'security.authorization_checker' => '?',
    'security.token_storage' => '?',
])));
