<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLnYbNi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLnYbNi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRLnYbNi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRLnYbNi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRLnYbNi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RLnYbNi',
    'container.build_id' => '69bf4356',
    'container.build_time' => 1575472658,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLnYbNi');
